### ISSUE TITLE
wrong number of arguments (given 2, expected 1) using Capybara 3.x

### ISSUE THREAD

**Issue by rjaros87** [appium/appium_capybara#38]
Using newest Capybara 3.2.1 during tests throw error:
```
ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/appium_capybara-1.5.0/lib/appium_capybara/driver/appium/node.rb:12:in `set'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/node/element.rb:93:in `block in set'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/node/base.rb:83:in `synchronize'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/node/element.rb:93:in `set'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/node/actions.rb:85:in `fill_in'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/session.rb:734:in `block (2 levels) in <class:Session>'
     # /Users/jaror/.rvm/gems/ruby-2.4.1/gems/capybara-3.2.1/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
```

After investigation:
Capybara 2.x https://github.com/teamcapybara/capybara/blob/2.17_stable/lib/capybara/node/element.rb
```
##
      #
      # Set the value of the form element to the given value.
      #
      # @param [String] value    The new value
      # @param [Hash{}] options  Driver specific options for how to set the value
      #
      # @return [Capybara::Node::Element]  The element
      def set(value, options={})
        options ||= {}

        driver_supports_options = (base.method(:set).arity != 1)

        unless options.empty? || driver_supports_options
          warn "Options passed to Capybara::Node#set but the driver doesn't support them"
        end

        synchronize do
          if driver_supports_options
            base.set(value, options)
          else
            base.set(value)
          end
        end
        return self
      end
```

Now https://github.com/teamcapybara/capybara/blob/master/lib/capybara/node/element.rb
```
##
      #
      # Set the value of the form element to the given value.
      #
      # @param [String] value    The new value
      # @param [Hash{}] options  Driver specific options for how to set the value. Take default values from {Capybara#default_set_options}
      #
      # @return [Capybara::Node::Element]  The element
      def set(value, **options)
        raise Capybara::ReadOnlyElementError, "Attempt to set readonly element with value: #{value}" if readonly?
        options = session_options.default_set_options.to_h.merge(options)
        synchronize { base.set(value, options) }
        self
      end
```

So they removed `driver_supports_options` and always call `base.set(value, options)`

In `appium_capybara` is like below https://github.com/appium/appium_capybara/blob/master/lib/appium_capybara/driver/appium/node.rb
```
# Override
    def set(value)
      native.clear
      send_keys(value)
    end
```

**Comment by KazuCocoa** [comment]
https://rubygems.org/gems/appium_capybara/versions/1.5.1
