### ISSUE TITLE
W3C actions sends wrong action id

### ISSUE THREAD

**Issue by luke-hill** [appium/appium_capybara#58]
## This is a
* [x] Bug report
* [ ] Question
* [ ] Feature Request

## Environment
- iOS12 iPhone 8
- iOS12 iPhone 11
- iOS13 iPhone 11

## Actual behaviour and steps to reproduce
`element.send_keys([:shift, :end])`

## Expected behaviour
```
ArgumentError, "You cannot send multiple keystrokes simultaneously to a mobile driven device"
```

## Actual behaviour
```
An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'" UserInfo={NSLocalizedDescription=Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'} (Selenium::WebDriver::Error::UnknownError)

UnknownError: An unknown server-side error occurred while processing the command. Original error: Error Domain=com.facebook.WebDriverAgent Code=1 "Only actions of '(
    pointer,  key
)' types are supported. 'key' is given instead for action with id 'keyboard'" UserInfo={NSLocalizedDescription=Only actions of '(
    pointer, key
)' types are supported. 'key' is given instead for action with id 'keyboard'}
    at errorFromW3CJsonCode (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/protocol/errors.js:780:25)
    at ProxyRequestError.getActualError (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/protocol/errors.js:663:14)
    at JWProxy.command (/usr/local/.browserstack/appium_1.17.0_bstack/node_modules/appium-base-driver/lib/jsonwp-proxy/proxy.js:265:8)
```
## Any additional comments

Maybe some more documentation would be good on this note.

**Comment by KazuCocoa** [comment]
https://github.com/appium/WebDriverAgent/blob/a1824895274c60798b506f31054e4ce1e0400c71/WebDriverAgentLib/Utilities/FBW3CActionsSynthesizer.m#L879-L890 is the error line.
I'm not so familiar with this library but will take a look when i have time after you attach logs as the above comment

**Comment by luke-hill** [comment]
You'll need to hand-hold a bit more in order to generate said logs. Sorry this stuff is really poorly documented or I am looking in the wrong location.

I don't want to send you my entire stack so I want to create something slimmed down, but need a way of generating the repo case.

**Comment by KazuCocoa** [comment]
Ok.
Then, can you share the log of begin/end of `element.send_keys` like https://github.com/appium/appium_capybara/issues/58#issuecomment-790004327 's attached log?
If I can take a look at what query was sent by your client, it should become a hint.

**Comment by luke-hill** [comment]
When you say log. I don't have any way of generating logs like yours.

The logging I'm using is

Selenium - DEBUG set on the Webdriver logger. I don't have any way to generate XCUITest / Appium logs.

**Comment by KazuCocoa** [comment]
Logs you can see when an appium server launches on your console.

e.g.
```
$ appium
[Appium] Welcome to Appium v1.21.0-beta.0 (REV f40a2070ba320b97b3c3d3fc610ca4aedbe32c2f)
[Appium] Appium REST http interface listener started on 0.0.0.0:4723
```

Then, the console will get more logs as I attached in a session.

**Comment by luke-hill** [comment]
Similar to bugs I have raised in the safaridriver webkit tracker, this isn't possible for me. As we don't start the appium client, we use a third party (browserstack).

**Comment by luke-hill** [comment]
EDIT: I can do this. I just wasn't aware how to. This will be done before the end of March.

@ me if I don't post them by then!

**Comment by luke-hill** [comment]
Hi @KazuCocoa I think I've found a way to obtain them are the logs a little like this

```
2021-03-29 08:42:36:386 - [HTTP] --> POST /wd/hub/session
2021-03-29 08:42:36:386 - [HTTP] {"capabilities":{"firstMatch":[{"newCommandTimeout":0,"platformName":"iOS","browserName":"safari","realMobile":"true","deviceName":"iPhone 11","safariIgnoreFraudWarning":true,"orientation":"PORTRAIT","deviceOrientation":"PORTRAIT","noReset":true}]}}
2021-03-29 08:42:36:387 - [debug] [W3C] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{"newCommandTimeout":0,"platformName":"iOS","browserName":"safari","realMobile":"true","deviceName":"iPhone 11","safariIgnoreFraudWarning":true,"orientation":"PORTRAIT","deviceOrientation":"PORTRAIT","noReset":true}]}]
2021-03-29 08:42:36:388 - [debug] [BaseDriver] Event 'newSessionRequested' logged at 1617007356387 (08:42:36 GMT+0000 (Coordinated Universal Time))
2021-03-29 08:42:36:394 - [BaseDriver] The following capabilities are not standard capabilities and should have an extension prefix:
2021-03-29 08:42:36:394 - [BaseDriver]   newCommandTimeout
2021-03-29 08:42:36:394 - [BaseDriver]   realMobile
2021-03-29 08:42:36:395 - [BaseDriver]   deviceName
2021-03-29 08:42:36:395 - [BaseDriver]   safariIgnoreFraudWarning
2021-03-29 08:42:36:395 - [BaseDriver]   orientation
2021-03-29 08:42:36:395 - [BaseDriver]   deviceOrientation
2021-03-29 08:42:36:395 - [BaseDriver]   noReset
2021-03-29 08:42:36:395 - [BaseDriver]   useXctestrunFile
2021-03-29 08:42:36:395 - [BaseDriver]   bootstrapPath
2021-03-29 08:42:36:395 - [BaseDriver]   browserstack.isTargetBased
2021-03-29 08:42:36:399 - [Appium] DeprecationWarning: 'automationName' capability was not provided. Future versions of Appium will require 'automationName' capability to be set for iOS sessions.
2021-03-29 08:42:36:400 - [Appium] Requested iOS support with version >= 10, using 'XCUITest' driver instead of UIAutomation-based driver, since the latter is unsupported on iOS 10 and up.
2021-03-29 08:42:37:131 - [Appium] Appium v1.20.2 creating new XCUITestDriver (v3.34.0) session
2021-03-29 08:42:37:134 - [debug] [BaseDriver] Creating session with W3C capabilities: {
2021-03-29 08:42:37:134 - [debug] [BaseDriver]   "alwaysMatch": {
2021-03-29 08:42:37:134 - [debug] [BaseDriver]     "appium:newCommandTimeout": 0,
```

**Comment by KazuCocoa** [comment]
The log seems right. Could you get the log when your client calls `send_keys`?

**Comment by luke-hill** [comment]
Hi there sorry for delay was on a holiday.

I'll update this in the coming week.

**Comment by luke-hill** [comment]
[appium-logs.txt](https://github.com/appium/appium_capybara/files/6350093/appium-logs.txt)

**Comment by KazuCocoa** [comment]
Thanks, I confirmed the log.
So far, I guess capybara issued its own send_keys actions, which is not by appium_lib/appium_lib_core.
I need to find more time to debug this.

Do you have time to ensure if this behavior happens well-known websites like Google?

So,:

1. open https://google.com
2. click the search field
3. Get current active element
4. element.send_keys([:shift, :end])

I don't have this capybara environment for now on my local, so it is helpful if you have time to check this for my further investigation.

**Comment by luke-hill** [comment]
Initial tests show this is a problem everywhere.

**Comment by luke-hill** [comment]
Bump @KazuCocoa

**Comment by KazuCocoa** [comment]
I have added test cases with `send_keys` as https://github.com/appium/appium_capybara/pull/60/files#diff-b2de4210f3178616088103cc95f066ef492939f4900be343d303dfbe6089c75bR26-R33
They worked like the below.

```
[HTTP] --> POST /wd/hub/session/5f3062e8-663a-4d37-bc7b-0d69c9260c47/element/BA000000-0000-0000-ED6B-000000000000/value
[HTTP] {"value":["","",""],"text":""}
[debug] [W3C (5f3062e8)] Calling AppiumDriver.setValue() with args: [["","",""],"BA000000-0000-0000-ED6B-000000000000","5f3062e8-663a-4d37-bc7b-0d69c9260c47"]
[debug] [XCUITest] Executing command 'setValue'
[debug] [WD Proxy] Matched '/element/BA000000-0000-0000-ED6B-000000000000/value' to command name 'setValue'
[debug] [Protocol Converter] Added 'text' property "" to 'setValue' request body
[debug] [WD Proxy] Proxying [POST /element/BA000000-0000-0000-ED6B-000000000000/value] to [POST http://127.0.0.1:8100/session/6A1D1803-9D60-4F63-BD7F-DDE47712F76C/element/BA000000-0000-0000-ED6B-000000000000/value] with body: {"value":["","",""],"text":""}
[debug] [W3C (5f3062e8)] Responding to client with driver.setValue() result: null
[HTTP] <-- POST /wd/hub/session/5f3062e8-663a-4d37-bc7b-0d69c9260c47/element/BA000000-0000-0000-ED6B-000000000000/value 200 629 ms - 14
```

**Comment by KazuCocoa** [comment]
mm, I guess your case was a different pattern.
Could you reproduce your case with this repository's example app..?

**Comment by luke-hill** [comment]
I'm no longer at this job, and my new job is a long way away from being able to test on firefox / mobile (Where the main issues occurred).

To reproduce simply try send multiple keys using a mobile device. i.e. use capybara and do `[:shift, :end]`

**Comment by KazuCocoa** [comment]
Okay, thanks. Then, probably test target specific behavior in capybara x Firefox. (I guess then capybara assumed the firefox was desktop's one)

On the native iOS app, the below command worked with this module without reported issue.

```
    e = capy_driver.find_custom(:predicate, 'value == "Placeholder text"').first
    e.send_keys [:shift, :end]

    e = Capybara.current_session.find(:xpath, '//XCUIElementTypeTextField[@value=""]')
    e.send_keys [:shift, :end]
```

Close for now.
