### ISSUE TITLE
Undefined method `reset' for #<Appium::Driver::...

### ISSUE THREAD

**Issue by ndbroadbent** [appium/appium_capybara#76]
My tests are crashing at the end when `appium_capybara` calls `@appium_driver.reset`.

```
    1.1) Failure/Error: ex.run

          NoMethodError:
            undefined method `reset' for #<Appium::Driver:0x0000000160cae0c0 @core=#<Appium::Core::Driver:0x0000000160cadf58 @delegate_target=#<Appium::Core::Driver:0x0000000160cadf58 ...>, @automation_name=:xcuitest, @custom_url="http://localhost:4723", @caps=#<Appium::Core::Base::Capabilities:0x0000000160cade68 @capabilities={:deviceName=>"iPad Pro (11-inch) (3rd generation)", :browserName=>"Safari", :automationName=>"xcuitest", :platformName=>"iOS", :platformVersion=>"15.5", "safari:useSimulator"=>true, :showSafariConsoleLog=>true, :noReset=>true, "newCommandTimeout"=>3600}>, @enable_idempotency_header=true, @default_wait=nil, @port=4723, @wait_timeout=30, @wait_interval=0.5, @listener=nil, @direct_connect=true, @device=:ios, @http_client=#<Appium::Http::Default:0x0000000160d46ed8 @open_timeout=nil, @read_timeout=nil, @additional_headers={}, @server_url=#<URI::HTTP http://localhost:4723/>, @common_headers={"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"appium/ruby_lib_core/9.2.0 (selenium/4.23.0 (ruby macosx))"}, @proxy=nil, @http=#<Net::HTTP localhost:4723 open=true>>, @driver=#<Appium::Core::Base::Driver:0x40eff5469193f42a browser=:safari>>, @caps=#<Appium::Core::Base::Capabilities:0x0000000160cade68 @capabilities={:deviceName=>"iPad Pro (11-inch) (3rd generation)", :browserName=>"Safari", :automationName=>"xcuitest", :platformName=>"iOS", :platformVersion=>"15.5", "safari:useSimulator"=>true, :showSafariConsoleLog=>true, :noReset=>true, "newCommandTimeout"=>3600}>, @custom_url="http://localhost:4723", @default_wait=0, @appium_port=4723, @appium_wait_timeout=30, @appium_wait_interval=0.5, @listener=nil, @appium_device=:ios, @automation_name=:xcuitest, @appium_debug=true, @sauce=#<Appium::SauceLabs:0x0000000160d47a90 @username=nil, @access_key=nil, @endpoint="ondemand.saucelabs.com:443/wd/hub">, @sauce_username=nil, @sauce_access_key=nil, @sauce_endpoint="ondemand.saucelabs.com:443/wd/hub", @driver=#<Appium::Core::Base::Driver:0x40eff5469193f42a browser=:safari>, @http_client=#<Appium::Http::Default:0x0000000160d46ed8 @open_timeout=nil, @read_timeout=nil, @additional_headers={}, @server_url=#<URI::HTTP http://localhost:4723/>, @common_headers={"Accept"=>"application/json", "Content-Type"=>"application/json; charset=UTF-8", "User-Agent"=>"appium/ruby_lib_core/9.2.0 (selenium/4.23.0 (ruby macosx))"}, @proxy=nil, @http=#<Net::HTTP localhost:4723 open=true>>, @appium_server_status={"ready"=>true, "message"=>"The server is ready to accept new connections", "build"=>{"version"=>"2.11.2", "git-sha"=>"8e8ce4a2f7fb6044c83101ffc12c57d1b15938e1", "built"=>"2024-07-23 20:32:35 +0100"}}>

                  @appium_driver.reset if @appium_driver
                                ^^^^^^
            Did you mean?  present?
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/appium_capybara-3.1.1/lib/appium_capybara/driver/appium/driver.rb:51:in `reset!'
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.40.0/lib/capybara/session.rb:132:in `reset!'
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.40.0/lib/capybara.rb:327:in `block in reset_sessions!'
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.40.0/lib/capybara.rb:327:in `reverse_each'
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.40.0/lib/capybara.rb:327:in `reset_sessions!'
          # /Users/ndbroadbent/.local/share/mise/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/capybara-3.40.0/lib/capybara/rspec.rb:20:in `block (2 levels) in <main>'
```

It looks like the `reset` method has been removed. I saw that `@appium_driver` does respond to a `restart` method.

**Comment by ndbroadbent** [comment]
I'm not sure if this is the right way to fix it, but I'm using this commit in my fork as a workaround: https://github.com/appium/appium_capybara/commit/97e81ccb0d9e6fda21385f2907b7d62d0fa0cb16

**Comment by KazuCocoa** [comment]
Yes, thanks. `restart` could be the alternative for this case.

**Comment by KazuCocoa** [comment]
3.1.2 should be ok.
