### ISSUE TITLE
undefined method `name' for #<Capybara::Selenium::ChromeNode:...>

### ISSUE THREAD

**Issue by ndbroadbent** [appium/appium_capybara#77]
Another issue caused by an override in appium_capybara:

```
Failure/Error: \e[0mfind(".folder-row[data-name='#{subfolder1.name}']").click

NoMethodError:
  undefined method `name' for #<Capybara::Selenium::ChromeNode:0x00007f6573f5eb20>

      %(#<Capybara::Node::Element name=#{@base.name}>)
                                              ^^^^^
./vendor/bundle/ruby/3.1.0/bundler/gems/appium_capybara-97e81ccb0d9e/lib/appium_capybara/ext/element_ext.rb:4:in `inspect'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/queries/selector_query.rb:106:in `description'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/queries/selector_query.rb:115:in `applied_description'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/node/finders.rb:312:in `block in synced_resolve'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/node/base.rb:84:in `synchronize'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/node/finders.rb:301:in `synced_resolve'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/node/finders.rb:60:in `find'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/session.rb:774:in `find'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/dsl.rb:52:in `call'
./vendor/bundle/ruby/3.1.0/gems/capybara-3.40.0/lib/capybara/dsl.rb:52:in `find'
```

(This is affecting a different capybara test that doesn't use appium.)

**Comment by ndbroadbent** [comment]
This is my workaround for this crash: https://github.com/appium/appium_capybara/commit/f9dd8b8359030adedd881f887d6439fa6922744b
